server:
  port: 9005
spring:
  application:
    name: leadnews-canal
  instance:
    prefer-ip-address: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 0ab8f057-b321-4055-897c-1c99316f65c0
  rabbitmq:
    host: 192.168.211.132
    port: 5672 #浏览器使用端口  15672
    username: guest
    password: guest
    virtual-host: /
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
#canal配置
canal:
  host: 192.168.211.132
  port: 11111

